import { supabase } from './supabaseClient'
export type Role='admin'|'professional'|'client'
export type Profile={id:string;full_name:string|null;phone:string|null;role:Role;active:boolean;avatar_url:string|null}
export async function getProfile(id:string){const {data,error}=await supabase.from('profiles').select('*').eq('id',id).maybeSingle();if(error)throw error;return data as Profile|null}
export async function getClientByUser(id:string){const {data,error}=await supabase.from('clients').select('*').eq('user_id',id).maybeSingle();if(error)throw error;return data}
export async function getProfessionalByUser(id:string){const {data,error}=await supabase.from('professionals').select('*').eq('user_id',id).maybeSingle();if(error)throw error;return data}
export async function getServices(){const {data,error}=await supabase.from('services').select('*').eq('active',true).order('name');if(error)throw error;return data??[]}
export async function getClients(){const {data,error}=await supabase.from('clients').select('*').eq('active',true).order('name');if(error)throw error;return data??[]}
export async function getAppointments(limit=100){const {data,error}=await supabase.from('appointments').select('*, clients(name,email), professionals(name), appointment_services(price,duration_minutes,services(name))').order('starts_at').limit(limit);if(error)throw error;return data??[]}
export async function getCommands(limit=100){const {data,error}=await supabase.from('commands').select('*, clients(name), professionals(name), command_items(*)').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data??[]}
export async function getFinancial(limit=100){const {data,error}=await supabase.from('financial_transactions').select('*').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data??[]}
export async function createCommand(input:{client_id:string;professional_id?:string|null;appointment_id?:string|null}){const {data,error}=await supabase.from('commands').insert({...input,status:'new',subtotal:0,discount:0,total:0}).select().single();if(error)throw error;return data}
export async function addCommandItem(input:{command_id:string;service_id:string;professional_id?:string|null;description:string;quantity:number;unit_price:number;unit_cost?:number;commission_percent?:number}){const {data,error}=await supabase.from('command_items').insert(input).select().single();if(error)throw error;return data}
export async function recalculateCommand(id:string){const {data:items,error:itemError}=await supabase.from('command_items').select('quantity,unit_price,unit_cost,commission_percent').eq('command_id',id);if(itemError)throw itemError;const subtotal=(items??[]).reduce((s,i)=>s+Number(i.quantity)*Number(i.unit_price),0);const cost=(items??[]).reduce((s,i)=>s+Number(i.quantity)*Number(i.unit_cost??0),0);const commission=(items??[]).reduce((s,i)=>s+Number(i.quantity)*Number(i.unit_price)*Number(i.commission_percent??0)/100,0);const {data,error}=await supabase.from('commands').update({subtotal,total:Math.max(0,subtotal),total_cost:cost,commission,profit:subtotal-cost-commission}).eq('id',id).select().single();if(error)throw error;return data}
export async function closeCommandOnline(id:string,gatewayId:string,fee:number,net:number,installments:number){const {error:updateError}=await supabase.from('commands').update({payment_gateway:gatewayId,payment_estimated_fee:fee,payment_estimated_net:net,payment_installments:installments}).eq('id',id);if(updateError)throw updateError;const {data,error}=await supabase.rpc('transition_command_state',{p_command_id:id,p_next:'pending_payment'});if(error)throw error;return data}
export async function markCommandPaidPdv(id:string,method:string,reference:string,amount:number){const {data:payment,error:paymentError}=await supabase.from('command_payments').insert({command_id:id,payment_method_id:method,amount,transaction_reference:reference}).select().single();if(paymentError)throw paymentError;const {data,error}=await supabase.rpc('transition_command_state',{p_command_id:id,p_next:'paid'});if(error)throw error;return {command:data,payment}}
