/* V16.11 — Final production auth gate. Never exposes stale-session errors on first load. */
(function(){
'use strict';
let sbUser=null,sbProfile=null,authSubmitting=false;
function authCss(){if(document.getElementById('v16-auth-css'))return;const st=document.createElement('style');st.id='v16-auth-css';st.textContent='.v16-auth-back{position:fixed;inset:0;z-index:99999;background:rgba(244,242,238,.96);display:grid;place-items:center;padding:20px}.v16-auth-back.v16-auth-hidden{display:none!important;pointer-events:none!important;visibility:hidden!important}.v16-auth-card{width:min(430px,100%);background:#fff;border:1px solid #e5e1da;border-radius:22px;padding:28px;box-shadow:0 20px 60px rgba(0,0,0,.12)}.v16-auth-card h1{margin:0 0 6px;font-size:24px}.v16-auth-card p{color:#777;margin:0 0 20px}.v16-auth-card input{width:100%;box-sizing:border-box;padding:13px 14px;border:1px solid #ddd6ce;border-radius:10px;margin:6px 0 12px;font-size:16px}.v16-auth-card button{width:100%;padding:13px;border:0;border-radius:10px;background:#171717;color:#fff;font-weight:700;font-size:15px;margin-top:4px}.v16-auth-card .secondary{background:#f1efeb;color:#222;margin-top:10px}.v16-auth-msg{min-height:22px;margin-top:12px;font-size:13px;color:#8a5b00}.v16-badge{display:inline-block;font-size:11px;background:#f1efeb;padding:5px 8px;border-radius:99px;margin-bottom:12px}';document.head.appendChild(st)}
function authOverlay(){authCss();let el=document.getElementById('v16-auth');if(el){el.classList.remove('v16-auth-hidden');return el}el=document.createElement('div');el.id='v16-auth';el.className='v16-auth-back';el.innerHTML='<div class="v16-auth-card"><span class="v16-badge">ED & DU • ACESSO SEGURO</span><h1>Entrar no aplicativo</h1><p>Acesse sua conta profissional ou de cliente.</p><input id="v16-email" type="email" autocomplete="email" placeholder="E-mail"><input id="v16-pass" type="password" autocomplete="current-password" placeholder="Senha"><button id="v16-login">Entrar</button><button id="v16-signup" class="secondary">Criar conta de cliente</button><div id="v16-msg" class="v16-auth-msg"></div></div>';document.body.appendChild(el);document.getElementById('v16-login').onclick=()=>login(false);document.getElementById('v16-signup').onclick=()=>login(true);return el}
function msg(t){const x=document.getElementById('v16-msg');if(x)x.textContent=t||''}
function ensureBridge(){if(window.__EDDU_NEON_READY)return window.__EDDU_NEON_READY;if(document.getElementById('v68-neon-bridge'))return new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(window.__EDDU_NEON_READY){clearInterval(t);resolve(window.__EDDU_NEON_READY)}else if(++n>80){clearInterval(t);reject(new Error('Neon bridge não inicializou'))}},100)});return new Promise((resolve,reject)=>{const s=document.createElement('script');s.id='v68-neon-bridge';s.src='v68-neon-production-bridge.js';s.onload=()=>window.__EDDU_NEON_READY?resolve(window.__EDDU_NEON_READY):reject(new Error('Neon bridge carregado sem promise'));s.onerror=()=>reject(new Error('Falha ao carregar a camada Neon'));document.head.appendChild(s)})}
async function waitClient(){const ready=await ensureBridge();if(ready)return ready;for(let i=0;i<80;i++){if(window.__EDDU_SB)return window.__EDDU_SB;await new Promise(r=>setTimeout(r,100))}throw new Error('Neon Auth/Data API não inicializou')}
function friendlyError(e){const s=String(e?.message||e||'');if(/failed to retrieve user session|jwk|jwks|key.*not found|not found.*key/i.test(s))return 'Sessão anterior inválida. Entre novamente para continuar.';return s||'Não foi possível autenticar. Tente novamente.'}
async function login(signup){if(authSubmitting)return;try{authSubmitting=true;msg(signup?'Criando sua conta...':'Entrando...');const sb=await waitClient(),email=document.getElementById('v16-email')?.value.trim(),password=document.getElementById('v16-pass')?.value||'';if(!email||password.length<6){msg('Informe e-mail e senha (mínimo de 6 caracteres).');return}const r=signup?await sb.auth.signUp({email,password,options:{data:{full_name:email.split('@')[0]}}}):await sb.auth.signInWithPassword({email,password});if(r?.error){msg(friendlyError(r.error));return}if(signup&&!r.data?.session){msg('Conta criada. Verifique seu e-mail para confirmar o acesso.');return}await bootUser(true)}catch(e){console.error('[EDDU Auth]',e);msg(friendlyError(e))}finally{authSubmitting=false}}
async function bootUser(force){const sb=await waitClient();let u=null;if(!force){try{const s=await sb.auth.getSession();u=s?.data?.session?.user||null}catch(e){console.warn('[EDDU Auth] sessão inicial ignorada',e);u=null}}else{try{u=(await sb.auth.getUser())?.data?.user||null}catch(e){throw e}}if(!u){sbUser=null;sbProfile=null;window.user=()=>null;window.profile=()=>null;authOverlay();msg('');return}sbUser=u;const pr=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();if(pr?.error&&/jwk|jwks/i.test(String(pr.error.message||'')))throw pr.error;sbProfile=pr.data||null;window.user=()=>sbUser;window.profile=()=>sbProfile;if(sbProfile){app.role=sbProfile.role==='client'?'client':'pro';app.page=app.role==='pro'?'dashboard':'home'}const [cr,sr,pm]=await Promise.all([sb.from('clients').select('*').order('name'),sb.from('services').select('*').order('id'),sb.from('payment_methods').select('name').eq('active',true).order('name')]);if(!cr.error&&Array.isArray(cr.data)&&cr.data.length){db.clients=cr.data.map(c=>({id:c.id,user_id:c.user_id,name:c.name,phone:c.phone||'',email:c.email||'',points:c.loyalty_points||0,term:false,anam:c.notes||'',history:[],anams:[]}));app.selectedClient=db.clients.find(c=>c.user_id===u.id)?.id||app.selectedClient||null}if(!sr.error&&Array.isArray(sr.data)&&sr.data.length){sr.data.forEach(x=>{const local=SERVICES.find(s=>s.n.toLowerCase()===String(x.name||'').toLowerCase()||s.n.replace('Fem','').toLowerCase()===String(x.name||'').replace('Fem','').toLowerCase());if(local){local.dbId=x.id;local.base=Number(x.price_base??x.price??0);local.long=Number(x.price_long??x.price??0);local.cost=Number(x.service_cost||0);local.time=Number(x.duration_minutes||60)}})}if(!pm.error&&pm.data?.length)db.settings.paymentMethods=pm.data.map(x=>x.name);const gate=document.getElementById('v16-auth');if(gate)gate.remove();if(typeof safeRender==='function')safeRender()}
window.EDDU_AUTH={login:()=>login(false),signup:()=>login(true),bootUser,getUser:()=>sbUser,getProfile:()=>sbProfile,signOut:async()=>{const sb=await waitClient();try{await sb.auth.signOut()}catch(e){}sbUser=null;sbProfile=null;window.user=()=>null;window.profile=()=>null;authOverlay();msg('')}};
window.user=()=>sbUser;window.profile=()=>sbProfile;
ensureBridge().then(()=>bootUser(false)).catch(e=>{console.error('[EDDU Auth] inicialização',e);authOverlay();msg('')});
})();
