-- ED & DU V33: organization isolation, command state machine and webhook idempotency.
create extension if not exists pgcrypto;
create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null,owner_user_id uuid references auth.users(id),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.organization_members(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null check(role in('owner','admin','professional','client')),active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,user_id));
create or replace function public.current_organization_id() returns uuid language sql stable security definer set search_path=public as $$select organization_id from public.organization_members where user_id=auth.uid() and active order by created_at limit 1$$;
create or replace function public.is_org_staff() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_members where organization_id=public.current_organization_id() and user_id=auth.uid() and active and role in('owner','admin','professional'))$$;
create or replace function public.is_org_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_members where organization_id=public.current_organization_id() and user_id=auth.uid() and active and role in('owner','admin'))$$;

do $$declare o uuid;u uuid;begin select id into u from public.profiles where role in('admin','professional') and active order by created_at limit 1;select id into o from public.organizations order by created_at limit 1;if o is null and u is not null then insert into public.organizations(name,owner_user_id) values('ED & DU | Terapia da Beleza',u) returning id into o;end if;if o is not null then insert into public.organization_members(organization_id,user_id,role) select o,id,case role when 'admin' then 'admin' when 'professional' then 'professional' else 'client' end from public.profiles where not exists(select 1 from public.organization_members m where m.organization_id=o and m.user_id=profiles.id);end if;end$$;

-- Core entities are organization-scoped. Existing rows are backfilled to the salon organization before NOT NULL.
DO $$DECLARE t text;BEGIN FOR t IN SELECT unnest(ARRAY['profiles','clients','professionals','services','appointments','appointment_services','commands','command_items','payment_methods','command_payments','financial_transactions','client_records','client_photos','payment_sessions']) LOOP EXECUTE format('alter table public.%I add column if not exists organization_id uuid references public.organizations(id)',t);EXECUTE format('update public.%I set organization_id=(select id from public.organizations order by created_at limit 1) where organization_id is null',t);EXECUTE format('alter table public.%I alter column organization_id set not null',t);END LOOP;END$$;

create table if not exists public.webhook_events(id uuid primary key default gen_random_uuid(),provider text not null,event_id text not null,transaction_id text,event_type text,payload jsonb not null,signature_valid boolean not null default false,processed_at timestamptz,created_at timestamptz not null default now(),unique(provider,event_id));
create unique index if not exists webhook_events_transaction_uq on public.webhook_events(provider,transaction_id) where transaction_id is not null;
alter table public.webhook_events enable row level security;

alter table public.commands drop constraint if exists commands_status_check;
alter table public.commands add constraint commands_status_check check(status in('new','open','pending_payment','paid','cancelled'));
update public.commands set status='open' where status='closed';
create or replace function public.transition_command_state(p_command_id uuid,p_next text) returns public.commands language plpgsql security invoker set search_path=public as $$declare s text;r public.commands;begin select status into s from public.commands where id=p_command_id and organization_id=public.current_organization_id() for update;if s is null then raise exception 'command_not_found';end if;if not((s='new' and p_next='open')or(s='open' and p_next='pending_payment')or(s='pending_payment' and p_next='paid')or(s in('new','open','pending_payment')and p_next='cancelled'))then raise exception 'invalid_command_transition';end if;update public.commands set status=p_next,closed_at=case when p_next='paid' then now() else closed_at end,updated_at=now() where id=p_command_id returning * into r;return r;end$$;

-- Core RLS policies use the active organization from the authenticated Supabase session.
do $$declare r record;begin for r in select tablename,policyname from pg_policies where schemaname='public' and tablename in('profiles','clients','professionals','services','appointments','appointment_services','commands','command_items','payment_methods','command_payments','financial_transactions','client_records','client_photos','payment_sessions') loop execute format('drop policy if exists %I on public.%I',r.policyname,r.tablename);end loop;end$$;
create policy profiles_org on public.profiles for select to authenticated using(organization_id=public.current_organization_id() and(id=auth.uid() or public.is_org_staff()));
create policy clients_org on public.clients for select to authenticated using(organization_id=public.current_organization_id() and(user_id=auth.uid() or public.is_org_staff()));
create policy clients_write on public.clients for all to authenticated using(organization_id=public.current_organization_id() and(user_id=auth.uid() or public.is_org_staff())) with check(organization_id=public.current_organization_id());
create policy professionals_org on public.professionals for select to authenticated using(organization_id=public.current_organization_id());
create policy services_org on public.services for select to authenticated using(organization_id=public.current_organization_id() and(active or public.is_org_staff()));
create policy services_staff on public.services for all to authenticated using(organization_id=public.current_organization_id() and public.is_org_staff()) with check(organization_id=public.current_organization_id());
create policy appointments_org on public.appointments for select to authenticated using(organization_id=public.current_organization_id() and(public.is_org_staff() or client_id in(select id from public.clients where user_id=auth.uid())));
create policy commands_org on public.commands for select to authenticated using(organization_id=public.current_organization_id() and(public.is_org_staff() or client_id in(select id from public.clients where user_id=auth.uid())));
create policy commands_staff on public.commands for all to authenticated using(organization_id=public.current_organization_id() and public.is_org_staff()) with check(organization_id=public.current_organization_id());
create policy command_items_org on public.command_items for select to authenticated using(organization_id=public.current_organization_id());
create policy command_items_staff on public.command_items for all to authenticated using(organization_id=public.current_organization_id() and public.is_org_staff()) with check(organization_id=public.current_organization_id());
create policy command_payments_org on public.command_payments for select to authenticated using(organization_id=public.current_organization_id());
create policy command_payments_staff on public.command_payments for all to authenticated using(organization_id=public.current_organization_id() and public.is_org_staff()) with check(organization_id=public.current_organization_id());
create policy financial_org on public.financial_transactions for select to authenticated using(organization_id=public.current_organization_id() and public.is_org_staff());
create policy financial_admin on public.financial_transactions for all to authenticated using(organization_id=public.current_organization_id() and public.is_org_admin()) with check(organization_id=public.current_organization_id());
